apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    component: backend
spec:
  containers:
    - name: todo-frontend-app
      image: natgwa/todo-backend:1.0.0
      ports:
        - containerPort: 8000
