version: "3.8"
services:
  mongodb:
    container_name: mongo-db
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
    env_file:
      - mongo.env
  backend:
    container_name: todo-backend-app
    build:
      context: ./backend
      #dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - backend.env
    depends_on:
      - mongodb
  frontend:
    container_name: todo-frontend-app
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodbdata: